services:
  - name: mayhem-forensics-worker
    type: worker
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "python app.py"
    packages:
      - ffmpeg
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
